fix issue

diff --git a/.github/workflows/export_streams.yml b/.github/workflows/export_streams.yml
--- a/.github/workflows/export_streams.yml
+++ b/.github/workflows/export_streams.yml
@@ -32,25 +32,38 @@ jobs:
     - name: Install dependencies
       run: |
         pip install pipenv
-        cd scripts
-        cd streams-export
+        cd scripts/streams-export
         pipenv install
+
+    - name: Debug - List directories and permissions
+      run: |
+        pwd
+        ls -la
+        mkdir -p temp_output
+        chmod 777 temp_output
+        ls -la temp_output
 
     - name: Run export script
       run: |
-        cd scripts
-        cd streams-export
-        
+        cd scripts/streams-export
         pipenv run pip list
-        pipenv run python export_streams.py ramvasuthevan /temp_output
+        pipenv run python export_streams.py  ramvasuthevan ../../temp_output
       env:
         PYTHONUNBUFFERED: 1
+
+    - name: Debug - Check temp_output after script run
+      run: |
+        ls -la temp_output || echo "temp_output directory not found or empty"
 
     - name: Move exported data
       run: |
         mkdir -p dogsheep-data/streams
-        find . -type d \( -name .git -o -name node_modules -o -name .jekyll-cache \) -prune -o -print | sed -e 's/[^-][^\/]*\//--/g' -e 's/^/ /' -e 's/-/|/'
-        cp -R scripts/streams-export/temp_output/* dogsheep-data/streams/
+        if [ -d "temp_output" ] && [ "$(ls -A temp_output)" ]; then
+          cp -R temp_output/* dogsheep-data/streams/
+        else
+          echo "temp_output directory not found or is empty"
+          exit 1
+        fi
 
     - name: Commit and push if changed
       run: |
